/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "dark-bg-color": "#252B42",
        "light-bg-color": "#FFFFFF",
        "primary-color": "#23A6F0",
        "secondary-color-1": "#23856D",
        "secondary-color-2": "#3C403D",
        "success-color": "#2DC071",
        "alert-color": "#E77C40",
        "danger-color": "#E74040",
        "muted-text-color": "#BDBDBD",
        "hover-color": "#2A7CC7",
        "disabled-element-color": "#8EC2F2",
        "muted-color": "#BDBDBD",
        "light-gray-1": "#FAFAFA",
        "light-gray-2": "#ECECEC",
        "faded-primary-color": "#B2E3FF",
        "faded-secondary-color-1": "#B9EAA8",
        "primary-text-color": "#23A6F0",
        "secondary-text-color-1": "#40BB15",
        "secondary-text-color-2": "#3C403D",
        "text-color": "#252B42",
        "light-text-color": "#FFFFFF",
        "second-text-color": "#737373",
      },
    },
    fontSize: {
      h1: ["58px", "80px"],
      h2: ["40px", "57px"],
      h3: ["24px", "32px"],
      h4: ["20px", "30px"],
      h5: ["16px", "22px"],
      h6: ["14px", "24px"],
      btnText: ["14px", "28px"],
      mobileMenu: ["30px", "45px"],
      paragraph: ["14px", "20px"],
      list: ["14px", "24px"],
    },
  },
  plugins: [],
};
